--- #YAML:1.0
name: Data-FormValidator
version: 3.71
author:
  - Mark Stosberg <mark@summersault.com>
abstract: |-
  Validates user input (usually from an HTML form) based
  on input profile.
license: perl
requires:
  Date::Calc: 0
  File::MMagic: 1.17
  Image::Size: 0
  MIME::Types: 1.005
  Regexp::Common: 0
  Test::More: 0
  overload: 0
provides:
  Data::FormValidator:
    file: lib/Data/FormValidator.pm
    version: 3.71
  Data::FormValidator::Constraints:
    file: lib/Data/FormValidator/Constraints.pm
    version: 3.7
  Data::FormValidator::Constraints::Dates:
    file: lib/Data/FormValidator/Constraints/Dates.pm
    version: 0.03
  Data::FormValidator::Constraints::Upload:
    file: lib/Data/FormValidator/Constraints/Upload.pm
    version: 0.71
  Data::FormValidator::ConstraintsFactory:
    file: lib/Data/FormValidator/ConstraintsFactory.pm
    version: 1.3
  Data::FormValidator::Filters:
    file: lib/Data/FormValidator/Filters.pm
    version: 3.50
  Data::FormValidator::Results:
    file: lib/Data/FormValidator/Results.pm
    version: 3.71
generated_by: Module::Build version 0.2611
