--- #YAML:1.0
name: Data-FormValidator
version: 4.20
author:
  - Mark Stosberg <mark@summersault.com>
abstract: |-
  Validates user input (usually from an HTML form) based
  on input profile.
license: perl
requires:
  Date::Calc: 5
  File::MMagic: 1.17
  Image::Size: 0
  MIME::Types: 1.005
  Regexp::Common: 0
  Test::More: 0
  overload: 0
provides:
  Data::FormValidator:
    file: lib/Data/FormValidator.pm
    version: 4.20
  Data::FormValidator::Constraints:
    file: lib/Data/FormValidator/Constraints.pm
    version: 4.14
  Data::FormValidator::Constraints::Dates:
    file: lib/Data/FormValidator/Constraints/Dates.pm
    version: 1.01
  Data::FormValidator::Constraints::RegexpCommon:
    file: lib/Data/FormValidator/Results.pm
    version: 4.14
  Data::FormValidator::Constraints::Upload:
    file: lib/Data/FormValidator/Constraints/Upload.pm
    version: 1.1
  Data::FormValidator::ConstraintsFactory:
    file: lib/Data/FormValidator/ConstraintsFactory.pm
    version: 1.4
  Data::FormValidator::Filters:
    file: lib/Data/FormValidator/Filters.pm
    version: 4.1
  Data::FormValidator::Results:
    file: lib/Data/FormValidator/Results.pm
    version: 4.14
generated_by: Module::Build version 0.2611
