--- #YAML:1.0
name: Data-FormValidator
version: 3.51
license: perl
distribution_type: module
requires:
  Date::Calc: 0
  File::MMagic: 1.17
  Image::Size: 0
  MIME::Types: 1.005
  Regexp::Common: 0
  Test::More: 0
recommends: {}
build_requires: {}
conflicts: {}
provides:
  Data::FormValidator:
    file: lib/Data/FormValidator.pm
    version: 3.51
  Data::FormValidator::Constraints:
    file: lib/Data/FormValidator/Constraints.pm
    version: 3.5
  Data::FormValidator::Constraints::Dates:
    file: lib/Data/FormValidator/Constraints/Dates.pm
    version: 0.02
  Data::FormValidator::Constraints::Upload:
    file: lib/Data/FormValidator/Constraints/Upload.pm
    version: 0.50_01
  Data::FormValidator::ConstraintsFactory:
    file: lib/Data/FormValidator/ConstraintsFactory.pm
    version: 1.3
  Data::FormValidator::Filters:
    file: lib/Data/FormValidator/Filters.pm
    version: 3.50
  Data::FormValidator::Results:
    file: lib/Data/FormValidator/Results.pm
    version: 3.51
generated_by: Module::Build version 0.21
