--- #YAML:1.0
name: Data-FormValidator
version: 4.60
author:
  - Mark Stosberg <mark@summersault.com>
abstract: |-
  Validates user input (usually from an HTML form) based
  on input profile.
license: perl
requires:
  Date::Calc: 5
  Email::Valid: 1
  File::MMagic: 1.17
  Image::Size: 0
  MIME::Types: 1.005
  Perl6::Junction: 1.1
  Regexp::Common: 0
  Scalar::Util: 0
  Test::More: 0
  overload: 0
  perl: 5.008
provides:
  Data::FormValidator:
    file: lib/Data/FormValidator.pm
    version: 4.60
  Data::FormValidator::Constraints:
    file: lib/Data/FormValidator/Constraints.pm
    version: 4.6
  Data::FormValidator::Constraints::Dates:
    file: lib/Data/FormValidator/Constraints/Dates.pm
    version: 4.60
  Data::FormValidator::Constraints::RegexpCommon:
    file: lib/Data/FormValidator/Results.pm
    version: 4.6
  Data::FormValidator::Constraints::Upload:
    file: lib/Data/FormValidator/Constraints/Upload.pm
    version: 4.6
  Data::FormValidator::ConstraintsFactory:
    file: lib/Data/FormValidator/ConstraintsFactory.pm
    version: 1.6
  Data::FormValidator::Filters:
    file: lib/Data/FormValidator/Filters.pm
    version: 4.6
  Data::FormValidator::Results:
    file: lib/Data/FormValidator/Results.pm
    version: 4.6
  Perl6::Junction:
    file: lib/Perl6/Junction.pm
    version: 1.10
  Perl6::Junction::All:
    file: lib/Perl6/Junction/All.pm
    version: 1.10
  Perl6::Junction::Any:
    file: lib/Perl6/Junction/Any.pm
    version: 1.10
  Perl6::Junction::None:
    file: lib/Perl6/Junction/None.pm
    version: 1.10
  Perl6::Junction::One:
    file: lib/Perl6/Junction/One.pm
    version: 1.10
generated_by: Module::Build version 0.2611
